export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  };
  
  export const userContants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  };
  export const Teachers = {
    GET_ALL_TEACHERS: "GET_ALL_TEACHERS",
    GET_ALL_TEACHERS_SUCCESS : "GET_ALL_TEACHERS_SUCCESS" ,
    GET_ALL_TEACHERS_FAILED : "GET_ALL_TEACHERS_FAILED",
    GET_ALL_TEACHERS_FAILED : "GET_ALL_TEACHERS_FAILED",
    CREATE_TEACHER: "CREATE_TEACHER",
    CREATE_TEACHER_SUCCESS: "CREATE_TEACHER_SUCCESS",
    CREATE_TEACHER_FAILED: "CREATE_TEACHER_FAILED",
    DELETE_TEACHER: "DELETE_TEACHER",
    DELETE_TEACHER_SUCCESS :"DELETE_TEACHER_SUCCESS",
    DELETE_TEACHER_FAILED :"DELETE_TEACHER_FAILED",
  };


  
  export const categoryConstansts = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
    UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
    UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
    UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
    DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
    DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
    DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
  };
  
  export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
  
    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",
  
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  };
  
  export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
    GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
    GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
  };
  
  export const pageConstants = {
    GET_ALL_PAGES: "GET_ALL_PAGES",
    GET_ALL_PAGES_SUCCESS : "GET_ALL_PAGES_SUCCESS" ,
    GET_ALL_PAGES_FAILED : "GET_ALL_PAGES_FAILED",
    GET_ALL_PAGES_FAILED : "GET_ALL_PAGES_FAILED",
    CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
    CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
    CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
    DELETE_PAGE_REQUEST: "DELETE_PAGE_REQUEST",
    DELETE_PAGE_SUCCESS: "DELETE_PAGE_SUCCESS",
    DELETE_PAGE_FAILURE: "DELETE_PAGE_FAILURE",
  };
  export const GroupConstants = {
    GET_ALL_GROUPS: "GET_ALL_GROUPS",
    GET_ALL_GROUPS_SUCCESS : "GET_ALL_GROUPS_SUCCESS" ,
    GET_ALL_GROUPS_FAILED : "GET_ALL_GROUPS_FAILED",
    GET_ALL_GROUPS_FAILED : "GET_ALL_GROUPS_FAILED",
    CREATE_GROUP_REQUEST: "CREATE_GROUP_REQUEST",
    CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
    CREATE_GROUP_FAILURE: "CREATE_GROUP_FAILURE",
    DELETE_GROUP_REQUEST: "DELETE_GROUP_REQUEST",
    DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
    DELETE_GROUP_FAILURE: "DELETE_GROUP_FAILURE",
  };
  
  export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
  };